// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: datasource.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Models {
  public static partial class DatasourcePlugin
  {
    static readonly string __ServiceName = "models.DatasourcePlugin";

    static readonly grpc::Marshaller<global::Models.DatasourceRequest> __Marshaller_models_DatasourceRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Models.DatasourceRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Models.DatasourceResponse> __Marshaller_models_DatasourceResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Models.DatasourceResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Models.DatasourceRequest, global::Models.DatasourceResponse> __Method_Query = new grpc::Method<global::Models.DatasourceRequest, global::Models.DatasourceResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Query",
        __Marshaller_models_DatasourceRequest,
        __Marshaller_models_DatasourceResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Models.DatasourceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DatasourcePlugin</summary>
    [grpc::BindServiceMethod(typeof(DatasourcePlugin), "BindService")]
    public abstract partial class DatasourcePluginBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Models.DatasourceResponse> Query(global::Models.DatasourceRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DatasourcePlugin</summary>
    public partial class DatasourcePluginClient : grpc::ClientBase<DatasourcePluginClient>
    {
      /// <summary>Creates a new client for DatasourcePlugin</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DatasourcePluginClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DatasourcePlugin that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DatasourcePluginClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DatasourcePluginClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DatasourcePluginClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Models.DatasourceResponse Query(global::Models.DatasourceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Query(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Models.DatasourceResponse Query(global::Models.DatasourceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Query, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Models.DatasourceResponse> QueryAsync(global::Models.DatasourceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Models.DatasourceResponse> QueryAsync(global::Models.DatasourceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Query, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DatasourcePluginClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DatasourcePluginClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(DatasourcePluginBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Query, serviceImpl.Query).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DatasourcePluginBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Query, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Models.DatasourceRequest, global::Models.DatasourceResponse>(serviceImpl.Query));
    }

  }
}
#endregion
